# Generated by Django 2.2.4 on 2019-10-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(max_length=32)),
                ('img', models.ImageField(upload_to='pics')),
                ('entity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField(max_length=32)),
                ('img', models.URLField()),
            ],
        ),
    ]
