# Generated by Django 2.2.5 on 2019-09-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='new_users',
        ),
    ]
