# Generated by Django 2.2.5 on 2019-09-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0005_auto_20190928_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='entity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
