# Generated by Django 2.2.5 on 2019-10-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0007_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='rst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('img', models.URLField(max_length=500)),
                ('adress', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='res',
        ),
    ]
