# Generated by Django 2.2.5 on 2019-10-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato', '0008_auto_20191002_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='rst',
            name='url',
            field=models.URLField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
